version: "3.8"

services:
  frontend:
    build:
      context: ./test-app
      dockerfile: Dockerfile
    container_name: react_frontend
    volumes:
      - ./build:/usr/share/nginx/html  # 빌드 결과를 nginx에 마운트
    restart: always

  nginx:
    image: nginx:stable-alpine
    container_name: nginx_server
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./build:/usr/share/nginx/html  # frontend 빌드 결과를 nginx가 읽음
    depends_on:
      - frontend
    restart: always
