rsion: "3.8"

services:
  frontend:
    build:
      context: ./test-app
      dockerfile: Dockerfile
    container_name: react_frontend
    working_dir: /app
    volumes:
      - ./test-app:/app
      - /app/node_modules
    command: ["npm", "run", "build"]
    restart: "no"

  nginx:
    image: nginx:stable-alpine
    container_name: nginx_server
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./test-app/build:/usr/share/nginx/html
    depends_on:
      - frontend
    restart: always
