# Node 공식 이미지 사용
FROM node:22-slim

# 작업 디렉토리 생성
WORKDIR /app

# package.json, package-lock.json만 복사 (캐시를 위해 분리)
COPY package*.json ./

# 의존성 설치
RUN npm install

# 앱 소스 복사
COPY . .

# React 앱 빌드
RUN npm run build
